export const ventures = [
  {slug:'kyburz-capital', name:'Kyburz Capital', domain:'kyburzcapital.com', type:'Capital concept', accent:'#f6f3ea', line:'Investment and capital management concept, kept conservative until entity and compliance are clear.', modules:['Investment thesis library','Deal notes','Capital dashboard','Compliance-safe education'], caution:'No investment advice, no performance claims, no solicitation language.'},
  {slug:'cain-union', name:'Cain Union', domain:'cainunion.com', type:'Financial management', accent:'#c58b5c', line:'Cashflow, bookkeeping, financial controls, and reporting for operators who need clarity.', modules:['Monthly close checklist','Cashflow view','Vendor/spend tracker','Bookkeeping handoff'], caution:'Avoid CPA/accounting claims unless formally supported.'},
  {slug:'mainframe-studio', name:'Mainframe Studio', domain:'mainframestud.io', type:'Business operating infrastructure', accent:'#5b7cfa', line:'Websites, intake, CRM, bookings, Drive, Slack/team, agents, dashboards, content, finance visibility, and approvals installed as one connected system.', modules:['CRM','Bookings','Content','Drive','Slack + Team','Finance','Agents','Approvals'], caution:'Agents draft and route; approval gates before publishing/spend/external sends.'},
  {slug:'jukes-diner', name:"Juke's Diner", domain:'jukesdiner.com', type:'Live operating proof', accent:'#ffca3a', line:'The real food truck proof lab: content, bookings, events, calendar flow, and local demand capture.', modules:['Book the truck','Menu/media library','Event calendar','Social content queue'], caution:'Live customer-facing brand; QA before public changes.'},
  {slug:'bel-air-intel', name:'Bel Air Intel', domain:'belairintel.com', type:'AI + systems', accent:'#8b5cf6', line:'AI agents, technical infrastructure, automation, dashboards, and strategic intelligence systems.', modules:['Agent systems','Dashboards','Automation briefs','Technical delivery'], caution:'Keep client secrets and internal systems scoped.'},
  {slug:'nanoeconomic', name:'Nanoeconomic', domain:'nanoeconomic.com', type:'Personal finance app', accent:'#23d18b', line:'Personal economics at human scale: cashflow, bills, goals, categories, and simple financial clarity.', modules:['Cashflow dashboard','Bills/subscriptions','Goals','Plain-language insights'], caution:'Demo data first; no bank connection, money movement, or investment advice yet.'},
  {slug:'policy-horizon', name:'Policy Horizon', domain:'policyhorizon.com', type:'Education + analysis', accent:'#7dd3fc', line:'Economics, public policy, and personal finance education explained clearly for normal people.', modules:['Briefings','Explainers','Personal finance lessons','Research archive'], caution:'Separate education from advisory/financial services.'},
  {slug:'wheels-circuit', name:'Wheels Circuit', domain:'wheelscircuit.com / wheelsbooking.com', type:'Food truck platform', accent:'#fb7185', line:'A food truck education and booking network designed to fill calendars, route overflow, and onboard operators into better systems.', modules:['Simple booking marketplace','Truck education hub','Operator onboarding','Calendar overflow network'], caution:'Start as lightweight booking/resource platform before overbuilding marketplace complexity.'}
];
export type Venture = typeof ventures[number];
