const basePath = process.env.GITHUB_PAGES === 'true' ? '/venture-demo-sites' : '';
const orgs = [
  {name:'Bel Air Intel', domain:'belairintel.com', interns:'2 interns', role:'agent systems, automation, dashboard QA, technical research', accent:'#8b5cf6', thesis:'The intelligence layer: agents, integrations, dashboards, technical infrastructure, and strategic automation.'},
  {name:'Cain Union', domain:'cainunion.com', interns:'1 intern', role:'bookkeeping ops, spend tagging, invoice workflows, finance dashboard QA', accent:'#c58b5c', thesis:'The control layer: cashflow visibility, bookkeeping workflows, invoicing, spend controls, and reporting.'},
  {name:'Mainframe Studio', domain:'mainframestud.io', interns:'3 interns', role:'websites, social content, client onboarding, Drive/Slack setup, brand systems', accent:'#5b7cfa', thesis:'The client-facing operating system: websites, CRM, bookings, content, team space, dashboards, and approval-gated execution.'}
];
export default function Trinity(){return <>
<nav className="nav"><div className="navin"><a className="brand" href={basePath || '/'}>← Venture Demo Lab</a><div className="navlinks"><a href="#staffing">Staffing</a><a href="#accounts">Accounts</a><a href="#operating-model">Model</a></div></div></nav>
<main>
<section className="routeHero"><div className="wrap"><div className="eyebrow">Three-company launch architecture</div><h1>Bel Air Intel, Cain Union, and Mainframe Studio.</h1><p className="lead">A clean operating structure for interns, websites, Google Workspace, Slack channels, Drive folders, dashboards, and the Bel Air Intel agent brain.</p><div className="path"><a className="button primary" href="#staffing">View staffing plan</a><a className="button" href="#accounts">Setup checklist</a></div></div></section>
<section id="staffing" className="section"><div className="wrap"><h2 className="big">Initial intern allocation</h2><div className="modules">{orgs.map(o=><div className="panel module" key={o.name} style={{borderColor:`${o.accent}66`}}><div className="eyebrow" style={{color:o.accent}}>{o.domain}</div><h3>{o.name}</h3><p className="muted">{o.thesis}</p><p><b>{o.interns}</b></p><p className="muted">Lane: {o.role}.</p></div>)}</div></div></section>
<section id="accounts" className="section"><div className="wrap split"><div><h2 className="big">Account structure</h2><p className="muted">Each company gets a separate public website, Google Workspace/email identity, Drive root, Slack lane, dashboard page, and approval rules. Shared agent summaries roll up into the Bel Air Intel brain.</p></div><div className="panel"><h2>Minimum setup per entity</h2><div className="pillrow">{['Domain','Google Workspace','SPF/DKIM/DMARC','Drive root','Slack channel','GitHub repo/project','Vercel project','Dashboard route','Credential inventory','Approval policy'].map(x=><span className="pill" key={x}>{x}</span>)}</div></div></div></section>
<section id="operating-model" className="section"><div className="wrap"><h2 className="big">Operating model</h2><div className="timeline"><div className="step"><span>01</span><b>Mainframe sells and packages the system.</b><p>Website, CRM, booking, content, Drive, Slack, dashboard, and workflows.</p></div><div className="step"><span>02</span><b>Bel Air Intel powers the brain.</b><p>Agents summarize, route tasks, watch dashboards, and prepare drafts with approval gates.</p></div><div className="step"><span>03</span><b>Cain Union controls the money layer.</b><p>Spend tracking, invoices, bookkeeping handoff, cashflow visibility, and monthly close rhythms.</p></div></div></div></section>
</main><footer className="footer"><div className="wrap">Trinity launch page — draft demo for intern recruiting and account setup.</div></footer>
</>}
